### ISSUE TITLE
client.payment.transfer() method can't be called properly

### ISSUE THREAD

**Issue by elouar25** [razorpay/razorpay-python#66]
Hello,

Calling the **client.payment.transfer("<PAYMENT_ID>")** method throws an error.

My code (file "test_transfer.py"):
```
import razorpay
client = razorpay.Client(auth=("<MY_API_KEY>", "<MY_API_SECRET>"))
client.payment.transfer("<MY_PAYMENT_ID>")
```

The response from Terminal:
```
Traceback (most recent call last):
  File "test_transfer.py", line 49, in <module>
    client.payment.transfer("pay_CYqsHlrwOFu8OQ")
  File "/Users/enguerrand/anaconda3/lib/python3.7/site-packages/razorpay/resources/payment.py", line 78, in transfer
    return self.post_url(url, data, **kwargs)
  File "/Users/enguerrand/anaconda3/lib/python3.7/site-packages/razorpay/resources/base.py", line 20, in post_url
    return self.client.post(url, data, **kwargs)
  File "/Users/enguerrand/anaconda3/lib/python3.7/site-packages/razorpay/client.py", line 155, in post
    return self.request('post', path, data=data, **options)
  File "/Users/enguerrand/anaconda3/lib/python3.7/site-packages/razorpay/client.py", line 136, in request
    raise BadRequestError(msg)
razorpay.errors.BadRequestError: The transfers field is required.
```

I guess the documentation is not up-to-date. Please help me how to make a transfer.

Thanks a ton!

**Comment by harman28** [comment]
Sorry for the delay here, noting the answer anyway in case someone else comes looking:

Correct payload: [Link](https://razorpay.com/docs/route/api/transfers/#request-parameters_)
